print("Please enter the following information so I can sell it for a profit!\n")
f_name=input("First name:")
l_name=input("Last name:")
Grade=int(input("Grade (9-12):"))
s_id=int(input("Student ID:"))
login=input("Login:")
Gpa=float(input("GPA (0.0-4.0):"))
print("\n\n")
print("Your information:\n")
print(f"\t\tLogin:{login} \n \t\tID:{s_id}\n \t\tName:{l_name}{f_name}\n \t\tGPA:{Gpa} \n \t\tGrade:{Grade}")