age=(int(input("How old are you?")))
height=(input("How tall are you?"))
weight=int(input("How much do you weight?"))
print("So, you're {} old, {} tall and {} heavy.".format(age,height,weight))
print(f"So, you're {age} old,{height} tall and {weight} heavy")