#file=open("/home/codeji/karka/name.txt",'w')
file=open("/home/codeji/karka/name.txt",'a')
f=file.write("\nheloo dude, i am")
# print(file)
file.close()
file=open("/home/codeji/karka/name.txt",'r')
f=file.read()
print(f)
file.close()